CREATE TABLE TablaA (
Id INT NOT NULL,
Nombre VARCHAR(50),
Descripcion VARCHAR(50),
PRIMARY KEY(Id)
)

CREATE TABLE TablaB(
Id INT NOT NULL,
Nombre VARCHAR(50),
Descripcion VARCHAR(50),
)

CREATE NONCLUSTERED INDEX IXTablaB ON TablaB(Id)


CREATE TABLE TablaC(
Id INT NOT NULL,
Nombre VARCHAR(50),
Descripcion VARCHAR(50),
)
CREATE CLUSTERED INDEX IXTablaC ON TablaC(Id)